### ISSUE TITLE
建议把spp作为可选择的

### ISSUE THREAD

**Issue by cole-dda** [eleme/node-ssdb#18]
在windows下不一定有编译环境，导致不能够编译spp，而不能安装，可以把spp作为可选择的，如果没有编译成功，就使用js的实现

**Comment by hit9** [comment]
是的，spp可以作为一个optional deps.

**Comment by hit9** [comment]
Fixed in #19. Available on npm as ssdb@0.2.2

**Comment by cole-dda** [comment]
thanks
