### ISSUE TITLE
ssdb并行请求，返回结果串了

### ISSUE THREAD

**Issue by mingyard** [eleme/node-ssdb#31]
我在使用ssdb的时候，发现并行请求ssdb返回结果会串。是我连接的方式有问题吗？

开发语言：node.js   版本：v0.10.43
ssdb扩展： node-ssdb  版本： v0.3.0

连接方式：
var ssdb = require('ssdb');
var config = require('../config.js');

exports.ssdbClient = function(){
    var client = ssdb.createPool({
        host: config.ssdb.host,
        port: config.ssdb.port,
        size: 5,
        timeout: 0
    });
    return client;
}
使用方法
async.each([
 '58e7168a9d7348c4606e26b1',
 '58e7168a9d7348c4606e26b1',
 '58dccb91319685b06ab517ee'], function(groupId, callback) {
 ssdbClient.acquire().zsize(typeConfig.groupKey + groupId, function(err,result){
        if (err) {
            return callback(err)
        }
        callback(null,result)
    })
})

这时就会出现返回结果串了。

**Comment by loserdong** [comment]
I very liked used SSDB, when I  had noticed this issue, I bring an old question back,

and I doubt there is something wrong when then ssdb client deal with concurrency situation,

so, I just test on my local host, and I found something wrong.

The issue will be recurrent as follow

1. set your local db and get data:

I use zset, and set there key 1-3 with size 1-3

```
ssdb 127.0.0.1:8888> zsize 1
1
(0.002 sec)
ssdb 127.0.0.1:8888> zsize 2
2
(0.000 sec)
ssdb 127.0.0.1:8888> zsize 3
3
(0.000 sec)
```

2. I write test javascript

```
var ssdb = require('ssdb')
var async = require('async')

var client = ssdb.createPool({
	host: '127.0.0.1',
	port: 8888,
	size: 1,
	timeout: 0
});

function test(key, callback) {
	client.acquire().zsize(key, function(err, result) {
		console.log("key = %j, size = %j", key, result)
		callback()
	})
}
 ```

3. with test case:

```
async.each([1, 2, 3], function(id, callback) {
	test(id, function(err, result) {
		callback()
	})
})
```
the output is：

```
key = 1, size = 2
key = 2, size = 3
key = 3, size = 1
```
Obvious，it's something wrong

4. but, when I run

```
async.eachSeries([1, 2, 3], function(id, callback) {
	test(id, function(err, result) {
		callback()
	})
})
```
it works well and output:

```
key = 1, size = 1
key = 2, size = 2
key = 3, size = 3
```
5. Pay attention, my pool size is just 1, but, I have there data, so? what does it happened when the ssdb client deal with concurrency situation?
